<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest" Version="4.0.2" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cripty.Application\Cripty.Application.csproj" />
		<ProjectReference Include="..\Cripty.Core\Cripty.Core.csproj" />
		<ProjectReference Include="..\Cripty.Cryptography\Cripty.Cryptography.csproj" />
		<ProjectReference Include="..\Cripty.Storage\Cripty.Storage.csproj" />
	</ItemGroup>

</Project>