<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	
<ItemGroup>
  <ProjectReference Include="..\Cripty.Core\Cripty.Core.csproj" />
  <ProjectReference Include="..\Cripty.Cryptography\Cripty.Cryptography.csproj" />
  <ProjectReference Include="..\Cripty.Storage\Cripty.Storage.csproj" />
</ItemGroup>

</Project>
